Add documentation, fix obsolete android build.grade
... but still fails to build the project

$ ./gradlew tasks --stacktrace

org.gradle.api.GradleScriptException: A problem occurred evaluating project ':AndroidSample'.
....
Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
	at com.android.build.gradle.BasePlugin.getLocalVersion(BasePlugin.groovy:491)
	at com.android.build.gradle.BasePlugin.<init>(BasePlugin.groovy:129)
	at com.android.build.gradle.AppPlugin.<init>(AppPlugin.groovy:40)
	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:62)
	at org.gradle.api.internal.plugins.DefaultPluginRegistry.loadPlugin(DefaultPluginRegistry.java:67)